# Generated by Django 4.1.3 on 2023-01-11 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_c', models.TextField(max_length=100, null=True)),
                ('mobile_c', models.CharField(max_length=50, null=True)),
                ('email_c', models.EmailField(max_length=100)),
                ('subject_c', models.CharField(max_length=100, null=True)),
                ('message_c', models.TextField(null=True)),
                ('Timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
