# Generated by Django 4.1.3 on 2023-01-14 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_message',
            name='response_a',
            field=models.TextField(null=True),
        ),
    ]
